### ISSUE TITLE
Links in installation tutorials are wrong

### ISSUE THREAD

**Issue by theUnusualSquid** [kubemq-io/kubemqctl#1]
I've tried to install kubectltools and the base URL is wrong on all of the releases.
It is:                         https://github.com/kubemq-io/kubemqctl/releases/
Where it should be: https://github.com/kubemq-io/kubetools/releases/

Not a breaking bug but it's a quick fix

**Comment by kubemq** [comment]
Hi,
We are going to release a complete new tool called kubemqctl which will
replace kubetools.
sorry for the inconvenience. This will happen within 2-3 days

**Comment by kubemq** [comment]
Hi,
Links are up and running,
Check it out our new kubemqctl app.
Lior,
