### ISSUE TITLE
problem in message body

### ISSUE THREAD

**Issue by veerapatyok** [kubemq-io/kubemqctl#11]
I sent message in kubemq but I found unnecessary string(`- (1)`)

example:
I sent message is `test-kubemq` but in log shown `test-kubemq - (1)`  

command: `kubemqctl queues send "hello-world-queue" "this is a queue message"`

in log: `[Message: 1] [channel: hello-world-queue] [client id: 7a4fcfb6-58b2-4fec-8807-7ac1fc04adb5] -> {id: 6dc054fe-0df1-4080-900e-4fe4b440076f, metadata: , body: this is a queue message - (1)}`

What does `{my message} - (1)` mean??

**Comment by kubemq** [comment]
this means that this is the message with the sequence id
