### ISSUE TITLE
how to list messages in a queue/event/event-store ?

### ISSUE THREAD

**Issue by bygui86** [kubemq-io/kubemqctl#13]
Hi guys,

first of all thank you for this amazing tool.

Maybe it's a stupid question but I don't find an answer in the documentation.

Is it possible to list messages in a queue/event/event-store using kubemqctl?

Thank you for the help

**Comment by kubemq** [comment]
Hi,
you can peek messages in queues with 
kubemqctl queue peek q1
as q1 is your channel name

**Comment by bygui86** [comment]
Adding flag for example `-m 5` I can get latest 5 messages in the queue right?

Is there a similar feature for event and event-store?

FYI: I would like to replace Kafka with KubeMQ in our stage-cluster, to understand the benefits and eventually convince the boss to replace it in production as well.
Is event-store the right channel type compatible with Kafka features like logs persistence?

**Comment by kubemq** [comment]
As event is real-time memory, there is no such feature.
In Events-Store you can subscribe to a channel and get the messages from specific position/time etc.
you can subscribe again with another client-id and get the same data again,
Event store is the compatible to Kafka and queues are more like Amazon SQS.
As we have many clients that switching from Kafka to KubeMQ, we can share with you the best practices on doing so.
you can contact me directly at lior.nabat@kubemq.io for more info

**Comment by bygui86** [comment]
Everything clear. I wanted to be sure! The documentation is good, but sometimes it's a bit too summarised and not always 100% clear.

Thank you very much for your answers!

I will contact you for sure if we decide to go productive!
