### ISSUE TITLE
create cluster in different namespace not creating services

### ISSUE THREAD

**Issue by philippnetural** [kubemq-io/kubemqctl#21]
Hello contributers,

I got a problem while creating a new cluster within an existing namespace. Create cluster works fine with the default namespace but if you want to set up the whole environment in a different namespace the service creation will fail. No instances will be started and the cluster will stay empty.

**kubemqctl create cluster -k <custom-key> --namespace=custom-namespace**
Current Kubernetes cluster context connection: <clustername>
Kubemq operator <custom-namespace>/kubemq-operator created.
Kubemq cluster <custom-namespace>/kubemq-cluster created.

**kubemqctl get cluster**                                                                    
Current Kubernetes cluster context connection: <clustername>
NAME                         DESIRED  READY  IMAGE  GRPC  REST  API  LICENSE-TO  LICENSE-TYPE  LICENSE-EXPIRE
<custom-namespace>/kubemq-cluster  0        0   

**Working solution with default namespace:**

**kubemqctl create cluster -k <custom-key>**
Kubemq operator kubemq/kubemq-operator created.
Kubemq cluster kubemq/kubemq-cluster created.

**kubemqctl get cluster**                                                                    
Current Kubernetes cluster context connection: <clustername>
NAME                         DESIRED  READY  IMAGE  GRPC  REST  API  LICENSE-TO  LICENSE-TYPE  LICENSE-EXPIRE
kubemq/kubemq-cluster  1        0      docker.io/kubemq/kubemq:latest  ClusterIP: 10.0.180.180:50000  ClusterIP: 10.0.76.235:9090  ClusterIP: 10.0.101.163:8080 <custom-email>  kubemq-pro-trial  2022-02-24

**Comment by kubemq** [comment]
Create is deprecated now, please use install
