### ISSUE TITLE
kubemqctl config reports error: the server could not find the requested resource (get kubemqclusters.core.k8s.kubemq.io)

### ISSUE THREAD

**Issue by jacreg** [kubemq-io/kubemqctl#24]
1. Kubemq installed on K8s: `kubectl apply -f https://deploy.kubemq.io/init` and  `kubectl apply -f https://deploy.kubemq.io/key/guid`
2. but cannot connfigure kubemqctl:  `kubemqctl config` reports:
`error: the server could not find the requested resource (get kubemqclusters.core.k8s.kubemq.io)`

Commands:
```
PowerShell 7.3.3
PS C:\Users\jr> Invoke-WebRequest https://github.com/kubemq-io/kubemqctl/releases/download/latest/kubemqctl.exe -OutFile 'C:\Program Files\kubemqctl\kubemqctl.exe'
PS C:\Users\jr> kubemqctl config
? Select Connection Type: Kubernetes cluster
? Select kube config path (press Enter for default):
Current Kubernetes cluster context connection: pesaks
? Select kubernetes cluster context: pesaks
Current Kubernetes cluster context connection: pesaks
error: the server could not find the requested resource (get kubemqclusters.core.k8s.kubemq.io)

PS C:\Users\jr> kubectl get customresourcedefinition.apiextensions.k8s.io/kubemqclusters.core.k8s.kubemq.io
NAME                                CREATED AT
kubemqclusters.core.k8s.kubemq.io   2023-03-28T09:07:42Z
PS C:\Users\jr> kubemqctl  -v
kubemqctl version v3.5.1
PS C:\Users\jr>
```

**Comment by riverar** [comment]
Ran into the same problem. The quickstart documentation doesn't seem to really work so given the upfront bad experience, I've unfortunately moved onto evaluating other solutions.

**Comment by kubemq** [comment]
Sorry to hear that,
You should download the latest version of kubemqctl, version v1.7.3

**Comment by riverar** [comment]
@kubemq Can verify that works! How strange, I'm going to re-trace my steps and figure out how `3.5.1` got onto my machine.

**Comment by jacreg** [comment]
OK, so issue is that the latest link in README.md points to version 3.5.1 instead of 3.7.1 
Put `v3.7.1` instead `latest` in ldownload link resolves issue :)
```
Invoke-WebRequest https://github.com/kubemq-io/kubemqctl/releases/download/v3.7.1/kubemqctl.exe -OutFile 'C:\Program Files\kubemqctl\kubemqctl.exe'
```
