### ISSUE TITLE
Confuse about param name and description

### ISSUE THREAD

**Issue by magicbank** [kubemq-io/kubemqctl#4]
in pkg/k8s/config/grpc.go line 14 and pkg/k8s/config/rest.go line 15
param name mean ENABLE but description tell DISABLE so what correct?

**Comment by kubemq** [comment]
The default in KubeMQ is true, this means if we want to change the
default we want to add env var that set  to false.
So the description set the action, the param set the value.
So if you want to disable grpc interface you should take action and make it
false.

**Comment by magicbank** [comment]
![Screen Shot 2019-10-28 at 16 37 12](https://user-images.githubusercontent.com/1920584/67667900-7507b100-f9a1-11e9-893e-be5ccae1e718.png)
from above screen short. i will answer "false" because i don't want disable this function. but it not correct. grpc will disable via configuration value "GRPC_ENABLE = false" receive from above question. you should ask question "(gRPC) Enable gRPC interface:" for expected "true" (i want enable grpc interface) answer.

so, the configuration question is not clear.

**Comment by kubemq** [comment]
thanks for clear this it out,
will fix it on next release
