### ISSUE TITLE
unable to connect to cluster

### ISSUE THREAD

**Issue by stephen-dahl** [kubemq-io/kubemqctl#6]
several commands including `kubemqctl cluster dashboard` return with an error with clusters created by rancher.
```
kubemqctl cluster dashboard
Current Kubernetes cluster context connection: dev
Download dashboard latest version...
Current Kubernetes cluster context connection: dev
Connecting To Kuberenets Cluster... Error: Error Upgrading Connection: Error Creating Request: Parse Https://Rancher.Ops.Mysite.Com%!F(MISSING)K8s%!F(MISSING)Clusters%!F(MISSING)C-xxxx/Api/V1/Namespaces/Kubemq/Pods/Kubemq-Cluster-0/Portforward: Invalid URL Escape "%!F(MISSING)"
```
actual server url from kube config `https://rancher.ops.mysite.com/k8s/clusters/c-xxxx`

**Comment by kubemq** [comment]
thanks for the report,
we are preparing for a new version very soon and we are going to depreciate the dashboard for another tool

**Comment by stephen-dahl** [comment]
I get this error with several commands, proxy does it also.

**Comment by juanrevello** [comment]
Hi! Any solution for this problem? I have the same problem when executing kubemqctl commands in a cluster managed by rancher
