### ISSUE TITLE
sending message to queue will unexpectedly modified before actual sending

### ISSUE THREAD

**Issue by coxa** [kubemq-io/kubemqctl#9]
Problem is here https://github.com/kubemq-io/kubemqctl/blob/2821345d21eef4dbc096f0f0b66480490770c6f4/cmd/queue/send.go#L106
I not understand why it should be modified

**Comment by kubemq** [comment]
we did this if we want to send a batch of messages with sequence numbers 
why this is a problem for you?

**Comment by coxa** [comment]
I just want to test my service by sending a json to queue but it fails because service can't parse json because of "- (0)" at the end

**Comment by kubemq** [comment]
got it,
we fix it asap,
stay tuned

**Comment by kubemq** [comment]
@coxa ,
fixed and release version v.2.3.1
let me know if this solved your problem

**Comment by coxa** [comment]
Awesome! Thank you a lot
It works as expected
